# Generated by Django 4.2 on 2024-06-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='templates/certificates/'),
        ),
    ]
