# Generated by Django 4.2 on 2024-06-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_certificates_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pdf', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='certificates',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
